events {}

http {

    server {
        listen 80;

        location /api/v1/ {
            proxy_pass http://main-service:8081/;
        }

        location /api/v1/items/ {
            proxy_pass http://items-service:8082/;
        }
    }

}
