events {}

http {

    server {
        listen 80;

        location /main/ {
            proxy_pass http://main-service:8081/;
        }

        location /items/ {
            proxy_pass http://items-service:8082/;
        }
    }

}
