events {}

http {

    server {
        listen 8080;

        location / {
            proxy_pass http://main-service:8081/;
        }

        location /main/ {
            proxy_pass http://main-service:8081/;
            proxy_redirect /swagger/ /main/swagger/index.html;
        }

        location /items/ {
            proxy_pass http://items-service:8082/;
            proxy_redirect /swagger/ /items/swagger/index.html;
        }
    }

}
